name: fvdb_garfvdb
channels:
  - conda-forge
  - nodefaults
dependencies:
  - blas=*=mkl
  - python=3.11
  - pytorch-gpu=2.4.1[build=cuda120*]
  - cuda-version=12.0
  - pip
  - git
  - gitpython
  - ipython
  - tqdm
  - numpy
  - tyro
  - scikit-learn
  - py-opencv
  - imageio
  - sam2
  - pyproj
  - transformers
  # 3dgs training
  - gdown
  - tensorboard
  - torchmetrics
  - viser
  - pip:
    - pye57
